apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: "localhost:6379"  # Update with your Redis server address
    - name: redisPassword
      value: ""  # Update if your Redis server requires a password
